<?php
/** Approved #27 Product 360°. */
defined('ABSPATH')||exit;
final class SSW_Product_360_Admin{
 public function __construct(){add_action('admin_menu',array($this,'menu'),26);}
 public function menu(){add_submenu_page('sheet-stock-sync-woo',__('Product 360°','sheet-stock-sync-woo'),__('Product 360°','sheet-stock-sync-woo'),'manage_woocommerce','ssw-product-360',array($this,'render'));}
 private function data($product_id){global $wpdb;$p=wc_get_product($product_id);if(!$p){return null;}$m=$wpdb->prefix.'ssw_product_metrics_daily';$sp=$wpdb->prefix.'ssw_supplier_products';$sup=$wpdb->prefix.'ssw_suppliers';$po=$wpdb->prefix.'ssw_purchase_orders';$pi=$wpdb->prefix.'ssw_purchase_order_items';$sales=$wpdb->prefix.'ssw_sales_daily';$snap=$wpdb->prefix.'ssw_inventory_snapshots_daily';
  $metric=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$m} WHERE product_id=%d ORDER BY metric_date DESC LIMIT 1",$product_id),ARRAY_A);if(!$metric){return array('product'=>$p,'metric'=>null);}
  $supplier=$wpdb->get_row($wpdb->prepare("SELECT sp.*,s.name supplier_name FROM {$sp} sp LEFT JOIN {$sup} s ON s.id=sp.supplier_id WHERE sp.product_id=%d AND sp.is_preferred=1 LIMIT 1",$product_id),ARRAY_A);
  $incoming=(float)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(GREATEST(i.ordered_qty-i.received_qty,0)),0) FROM {$pi} i INNER JOIN {$po} p2 ON p2.id=i.po_id WHERE i.product_id=%d AND p2.status IN ('approved','ordered','shipped','partially_received')",$product_id));
  $next_eta=$wpdb->get_var($wpdb->prepare("SELECT MIN(p2.expected_at) FROM {$pi} i INNER JOIN {$po} p2 ON p2.id=i.po_id WHERE i.product_id=%d AND i.ordered_qty>i.received_qty AND p2.status IN ('approved','ordered','shipped','partially_received')",$product_id));
  $s30=$wpdb->get_row($wpdb->prepare("SELECT COALESCE(SUM(units),0) units,COALESCE(SUM(revenue),0) revenue FROM {$sales} WHERE product_id=%d AND fact_date>=DATE_SUB(%s,INTERVAL 29 DAY) AND fact_date<=%s",$product_id,$metric['metric_date'],$metric['metric_date']),ARRAY_A);
  $forecast=(float)$metric['weighted_velocity']*30;$risk=SSW_Inventory_Intelligence::revenue_at_risk($forecast,(float)$metric['available_quantity'],$incoming,(float)$metric['avg_realized_price']);
  $oos=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM (SELECT snapshot_date,SUM(quantity) q FROM {$snap} WHERE product_id=%d AND snapshot_date>=DATE_SUB(%s,INTERVAL 29 DAY) AND snapshot_date<=%s GROUP BY snapshot_date HAVING q<=0) x",$product_id,$metric['metric_date'],$metric['metric_date']));$lost=SSW_Inventory_Intelligence::estimated_lost_sales((float)$metric['weighted_velocity'],$oos,(float)$metric['avg_realized_price']);
  $days=$metric['last_sale_date']?max(0,(int)floor((strtotime($metric['metric_date'])-strtotime($metric['last_sale_date']))/DAY_IN_SECONDS)):9999;$health=SSW_Inventory_Intelligence::health_score(array('availability'=>(float)$metric['available_quantity']<=0?0:((null!==$metric['days_of_stock']&&(float)$metric['days_of_stock']<14)?45:100),'excess_aging'=>$days>180?5:($days>90?25:($days>60?50:100)),'demand'=>(float)$metric['weighted_velocity']>0?100:20));
  $recommendation='healthy';if((float)$metric['available_quantity']<=0){$recommendation='stockout';}elseif(null!==$metric['days_of_stock']&&$supplier&&(float)$metric['days_of_stock']<(float)$supplier['lead_time_days']&&$incoming<=0){$recommendation='order_now';}elseif($days>90){$recommendation='reduce_or_stop_reorder';}
  return compact('p','metric','supplier','incoming','next_eta','s30','risk','lost','oos','days','health','recommendation');
 }
 public function render(){if(!current_user_can('manage_woocommerce')){wp_die(esc_html__('Permission denied.','sheet-stock-sync-woo'));}$id=isset($_GET['product_id'])?absint($_GET['product_id']):0;$d=$id?$this->data($id):null;?><div class="wrap"><h1><?php esc_html_e('Product 360°','sheet-stock-sync-woo');?></h1><form method="get" action="<?php echo esc_url(admin_url('admin.php'));?>"><input type="hidden" name="page" value="ssw-product-360"><input type="number" min="1" name="product_id" value="<?php echo esc_attr($id);?>" required> <button class="button"><?php esc_html_e('Open product','sheet-stock-sync-woo');?></button></form><?php if($id&&!$d):?><div class="notice notice-error inline"><p><?php esc_html_e('Product not found.','sheet-stock-sync-woo');?></p></div><?php elseif($d&&empty($d['metric'])):?><div class="notice notice-info inline"><p><?php esc_html_e('Product exists but analytics history is not ready yet.','sheet-stock-sync-woo');?></p></div><?php elseif($d):$p=$d['p'];$m=$d['metric'];?><h2><?php echo esc_html($p->get_name());?> <code><?php echo esc_html($p->get_sku());?></code></h2><table class="widefat striped" style="max-width:900px"><tbody>
 <tr><th>Price</th><td><?php echo wp_kses_post(wc_price($p->get_price()));?></td><th>Stock</th><td><?php echo esc_html($m['available_quantity']);?></td></tr><tr><th>Velocity</th><td><?php echo esc_html(number_format_i18n($m['weighted_velocity'],2));?>/day</td><th>Stock cover</th><td><?php echo null===$m['days_of_stock']?'—':esc_html(number_format_i18n($m['days_of_stock'],1).' days');?></td></tr>
 <tr><th>Projected stockout</th><td><?php echo esc_html($m['projected_stockout_date']?:'—');?></td><th>Incoming / next ETA</th><td><?php echo esc_html($d['incoming'].' / '.($d['next_eta']?:'—'));?></td></tr><tr><th>30d revenue / units</th><td><?php echo wp_kses_post(wc_price($d['s30']['revenue']));?> / <?php echo esc_html($d['s30']['units']);?></td><th>Revenue at Risk</th><td><?php echo wp_kses_post(wc_price($d['risk']['revenue_at_risk']));?></td></tr>
 <tr><th>Estimated Lost Sales</th><td><?php echo wp_kses_post(wc_price($d['lost']['estimated_lost_revenue']));?> (<?php echo esc_html($d['oos']);?> OOS days)</td><th>Health</th><td><?php echo esc_html(number_format_i18n($d['health']['score'],1).'/100 '.$d['health']['status']);?></td></tr><tr><th>Supplier inputs</th><td><?php echo esc_html($d['supplier']?$d['supplier']['supplier_name']:'—');?></td><th>Cost / MOQ / lead time</th><td><?php echo $d['supplier']?esc_html($d['supplier']['cost'].' '.$d['supplier']['currency'].' / '.$d['supplier']['moq'].' / '.$d['supplier']['lead_time_days'].'d'):'—';?></td></tr><tr><th>Slow / dead</th><td><?php echo esc_html(SSW_Inventory_Intelligence::aging_bucket($d['days']));?></td><th>Recommendation</th><td><strong><?php echo esc_html($d['recommendation']);?></strong></td></tr></tbody></table><?php endif;?></div><?php}
}
