<?php
/** Approved #24 deterministic anomaly detection. */
defined('ABSPATH')||exit;
final class SSW_Anomaly_Detector{
 public static function sales_velocity($recent,$baseline,$min_baseline=0.2){$recent=max(0,(float)$recent);$baseline=max(0,(float)$baseline);if($baseline<(float)$min_baseline){return null;}$ratio=$recent/$baseline;if($ratio>=2.5){return array('type'=>'sales_spike','severity'=>'warning','ratio'=>$ratio,'recent'=>$recent,'baseline'=>$baseline);}if($ratio<=0.35){return array('type'=>'sales_drop','severity'=>'warning','ratio'=>$ratio,'recent'=>$recent,'baseline'=>$baseline);}return null;}
 private static function key($value){$value=strtolower(trim((string)$value));return function_exists('sanitize_key')?sanitize_key($value):preg_replace('/[^a-z0-9_\-]/','',$value);}
 public static function stock_movement($delta,$stock_before,$source,$threshold_percent=20){$delta=(float)$delta;$before=max(1,abs((float)$stock_before));$source=self::key($source);$expected=array('woocommerce_order','purchase_order','bundle_sale','bundle_restore');if(in_array($source,$expected,true)){return null;}$pct=abs($delta)/$before*100;if(abs($delta)>=10&&$pct>=(float)$threshold_percent){return array('type'=>'unexplained_stock_change','severity'=>'warning','delta'=>$delta,'percent'=>$pct,'source'=>$source);}return null;}
 public static function price_change($before,$after,$threshold_fraction=0.30){$before=(float)$before;$after=(float)$after;if($before<=0){return null;}$change=abs($after-$before)/$before;if($change>=(float)$threshold_fraction){return array('type'=>'price_change','severity'=>'critical','before'=>$before,'after'=>$after,'change_fraction'=>$change);}return null;}
 public static function oos_spike($current,$baseline,$multiplier=3.0){$current=max(0,(int)$current);$baseline=max(0,(float)$baseline);if($baseline<1){return $current>=5?array('type'=>'oos_spike','severity'=>'critical','current'=>$current,'baseline'=>$baseline):null;}return $current>=$baseline*(float)$multiplier?array('type'=>'oos_spike','severity'=>'critical','current'=>$current,'baseline'=>$baseline):null;}
 public static function to_alert($anomaly,$product_id=0){if(!$anomaly){return null;}$type=$anomaly['type'];$id=function_exists('absint')?absint($product_id):abs((int)$product_id);return array('type'=>$type,'severity'=>isset($anomaly['severity'])?$anomaly['severity']:'warning','product_id'=>$id,'dedupe_key'=>SSW_Alerts::dedupe_key($type,array('product_id'=>$id)),'context'=>$anomaly);}
 public static function evaluate_latest_products($limit=100){global $wpdb;$metrics=$wpdb->prefix.'ssw_product_metrics_daily';$date=$wpdb->get_var("SELECT MAX(metric_date) FROM {$metrics}");if(!$date){return 0;}$rows=$wpdb->get_results($wpdb->prepare("SELECT product_id,velocity_7d,velocity_30d FROM {$metrics} WHERE metric_date=%s LIMIT %d",$date,min(250,max(1,(int)$limit))),ARRAY_A);$count=0;foreach($rows as $r){$a=self::sales_velocity((float)$r['velocity_7d'],(float)$r['velocity_30d']);if($a&&SSW_Alerts::persist(self::to_alert($a,(int)$r['product_id']))){$count++;}}return $count;}
}
