<?php
/** Approved #39 weekly report collection, persistence and delivery. */
defined('ABSPATH')||exit;
final class SSW_Weekly_Report_Service{
 const CRON='ssw_weekly_executive_report'; const TYPE='weekly_executive';
 public function __construct(){add_filter('cron_schedules',array($this,'cron_schedules'));add_action('admin_init',array($this,'ensure_schedule'));add_action(self::CRON,array($this,'run_scheduled'));}
 public function cron_schedules($s){if(!isset($s['ssw_weekly'])){$s['ssw_weekly']=array('interval'=>7*DAY_IN_SECONDS,'display'=>'Once Weekly');}return $s;}
 public function ensure_schedule(){if(!wp_next_scheduled(self::CRON)){wp_schedule_event(strtotime('next monday 07:00'),'ssw_weekly',self::CRON);}}
 public static function clear_schedule(){wp_clear_scheduled_hook(self::CRON);}
 public function run_scheduled(){$payload=self::generate(null,true);if(!$payload||!get_option('ssw_weekly_report_email_enabled',0)){return;}$to=sanitize_email(get_option('ssw_weekly_report_email',get_option('admin_email')));if(!$to){return;}wp_mail($to,__('Woo Hoo Manager — Weekly Executive Report','sheet-stock-sync-woo'),self::email_text($payload));}
 public static function generate($period_end=null,$persist=true){global $wpdb;$end=self::date($period_end?:current_time('Y-m-d'));if(!$end){return false;}$start=gmdate('Y-m-d',strtotime($end.' -6 days'));$prev_end=gmdate('Y-m-d',strtotime($start.' -1 day'));$prev_start=gmdate('Y-m-d',strtotime($prev_end.' -6 days'));$sales=$wpdb->prefix.'ssw_sales_daily';$current=self::sales($sales,$start,$end);$previous=self::sales($sales,$prev_start,$prev_end);$inventory=self::inventory($end,$start);$previous_inventory=self::inventory($prev_end,$prev_start);$alerts=$wpdb->prefix.'ssw_alerts';$current['critical_alerts']=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$alerts} WHERE state='open' AND severity='critical'");$current['warning_alerts']=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$alerts} WHERE state='open' AND severity='warning'");$current['bundle_opportunities']=(int)$wpdb->get_var("SELECT COUNT(*) FROM {$alerts} WHERE state='open' AND type='bundle_opportunity'");$current['purchasing_cash']=self::purchasing_cash($end);$current['period_start']=$start;$current['period_end']=$end;$previous['health_average']=$previous_inventory['health_average'];$current=array_merge($current,$inventory);$payload=SSW_Weekly_Report::build_payload($current,$previous);$payload['data_quality']=array('metric_date'=>$inventory['metric_date'],'products_analysed'=>$inventory['products_analysed'],'state'=>$inventory['products_analysed']?'deterministic':'insufficient_data');if($persist){self::persist($payload);}return $payload;}
 private static function sales($table,$start,$end){global $wpdb;$r=$wpdb->get_row($wpdb->prepare("SELECT COALESCE(SUM(revenue),0) revenue,COALESCE(SUM(units),0) units,COALESCE(SUM(orders_count),0) orders FROM {$table} WHERE fact_date BETWEEN %s AND %s",$start,$end),ARRAY_A);return array('revenue'=>(float)$r['revenue'],'units'=>(float)$r['units'],'orders'=>(int)$r['orders']);}
 private static function inventory($end,$start){global $wpdb;$m=$wpdb->prefix.'ssw_product_metrics_daily';$snap=$wpdb->prefix.'ssw_inventory_snapshots_daily';$po=$wpdb->prefix.'ssw_purchase_orders';$pi=$wpdb->prefix.'ssw_purchase_order_items';$f=$wpdb->prefix.'ssw_forecasts';$date=$wpdb->get_var($wpdb->prepare("SELECT MAX(metric_date) FROM {$m} WHERE metric_date<=%s",$end));if(!$date){return array('revenue_at_risk'=>0.0,'estimated_lost_sales'=>0.0,'stockouts'=>0,'dead_slow_count'=>0,'health_average'=>null,'metric_date'=>null,'products_analysed'=>0);}$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$m} WHERE metric_date=%s ORDER BY product_id LIMIT 1000",$date),ARRAY_A);$risk_total=0;$lost_total=0;$stockouts=0;$dead=0;$health_total=0;$health_count=0;foreach($rows as $r){$id=absint($r['product_id']);$incoming=(float)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(GREATEST(i.ordered_qty-i.received_qty,0)),0) FROM {$pi} i INNER JOIN {$po} p ON p.id=i.po_id WHERE i.product_id=%d AND p.status IN ('approved','ordered','shipped','partially_received')",$id));$forecast=$wpdb->get_var($wpdb->prepare("SELECT forecast_qty FROM {$f} WHERE product_id=%d AND horizon_days=30 AND generated_for_date<=%s ORDER BY generated_for_date DESC,FIELD(model_version,'seasonal_month_v1','weighted_velocity_v1') ASC LIMIT 1",$id,$date));$forecast=null===$forecast?(float)$r['weighted_velocity']*30:(float)$forecast;$risk=SSW_Inventory_Intelligence::revenue_at_risk($forecast,(float)$r['available_quantity'],$incoming,(float)$r['avg_realized_price']);$risk_total+=$risk['revenue_at_risk'];$oos=(int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM (SELECT snapshot_date,SUM(quantity) q FROM {$snap} WHERE product_id=%d AND snapshot_date BETWEEN %s AND %s GROUP BY snapshot_date HAVING q<=0) x",$id,$start,$end));$lost=SSW_Inventory_Intelligence::estimated_lost_sales((float)$r['weighted_velocity'],$oos,(float)$r['avg_realized_price']);$lost_total+=$lost['estimated_lost_revenue'];if((float)$r['available_quantity']<=0){$stockouts++;}$days=$r['last_sale_date']?max(0,(int)floor((strtotime($date)-strtotime($r['last_sale_date']))/DAY_IN_SECONDS)):9999;if($days>=91&&(float)$r['available_quantity']>0){$dead++;}$availability=(float)$r['available_quantity']<=0?0:(null!==$r['days_of_stock']&&(float)$r['days_of_stock']<14?45:100);$aging=$days>180?5:($days>90?25:($days>60?50:100));$demand=(float)$r['weighted_velocity']>0?100:20;$h=SSW_Inventory_Intelligence::health_score(array('availability'=>$availability,'excess_aging'=>$aging,'demand'=>$demand,'margin'=>null));if(null!==$h['score']){$health_total+=$h['score'];$health_count++;}}return array('revenue_at_risk'=>round($risk_total,4),'estimated_lost_sales'=>round($lost_total,4),'stockouts'=>$stockouts,'dead_slow_count'=>$dead,'health_average'=>$health_count?round($health_total/$health_count,2):null,'metric_date'=>$date,'products_analysed'=>count($rows));}
 private static function purchasing_cash($end){global $wpdb;$m=$wpdb->prefix.'ssw_product_metrics_daily';$sp=$wpdb->prefix.'ssw_supplier_products';$po=$wpdb->prefix.'ssw_purchase_orders';$pi=$wpdb->prefix.'ssw_purchase_order_items';$date=$wpdb->get_var($wpdb->prepare("SELECT MAX(metric_date) FROM {$m} WHERE metric_date<=%s",$end));if(!$date){return array();}$rows=$wpdb->get_results($wpdb->prepare("SELECT m.product_id,m.weighted_velocity,m.available_quantity,m.confidence_state,s.cost,s.currency,s.moq,s.units_per_box,s.lead_time_days FROM {$m} m INNER JOIN {$sp} s ON s.product_id=m.product_id AND s.is_preferred=1 WHERE m.metric_date=%s AND m.weighted_velocity>0 LIMIT 1000",$date),ARRAY_A);$cash=array();foreach($rows as $r){$incoming=(float)$wpdb->get_var($wpdb->prepare("SELECT COALESCE(SUM(GREATEST(i.ordered_qty-i.received_qty,0)),0) FROM {$pi} i INNER JOIN {$po} p ON p.id=i.po_id WHERE i.product_id=%d AND p.status IN ('approved','ordered','shipped','partially_received')",absint($r['product_id'])));$plan=SSW_Purchasing_Planner::plan_product(array('as_of_date'=>$end,'daily_velocity'=>$r['weighted_velocity'],'on_hand'=>$r['available_quantity'],'incoming'=>$incoming,'lead_time_days'=>$r['lead_time_days'],'safety_stock_days'=>5,'moq'=>$r['moq'],'pack_size'=>$r['units_per_box'],'unit_cost'=>$r['cost'],'currency'=>$r['currency'],'confidence'=>$r['confidence_state'],'horizon_days'=>90));if(empty($plan['suggested_order_date'])||null===$plan['expected_cash']){continue;}$cur=$plan['currency'];$cash[$cur]=isset($cash[$cur])?$cash[$cur]+$plan['expected_cash']:$plan['expected_cash'];}return $cash;}
 public static function persist($payload){global $wpdb;$t=$wpdb->prefix.'ssw_reports';$now=current_time('mysql');$json=wp_json_encode($payload);$sql="INSERT INTO {$t} (report_type,period_start,period_end,payload_json,created_at,updated_at) VALUES (%s,%s,%s,%s,%s,%s) ON DUPLICATE KEY UPDATE payload_json=VALUES(payload_json),updated_at=VALUES(updated_at)";return false!==$wpdb->query($wpdb->prepare($sql,self::TYPE,$payload['period']['start'],$payload['period']['end'],$json,$now,$now));}
 public static function latest(){global $wpdb;$t=$wpdb->prefix.'ssw_reports';$row=$wpdb->get_row($wpdb->prepare("SELECT payload_json FROM {$t} WHERE report_type=%s ORDER BY period_end DESC,id DESC LIMIT 1",self::TYPE),ARRAY_A);if(!$row){return null;}$p=json_decode($row['payload_json'],true);return is_array($p)?$p:null;}
 public static function email_text($p){$lines=array('Woo Hoo Manager — Weekly Executive Report',$p['period']['start'].' → '.$p['period']['end'],'','Revenue: '.$p['sales']['revenue'].' | Orders: '.$p['sales']['orders'].' | Units: '.$p['sales']['units'],'Revenue at Risk: '.$p['inventory']['revenue_at_risk'],'Estimated Lost Sales: '.$p['inventory']['estimated_lost_sales'],'Stockouts: '.$p['inventory']['stockouts'].' | Slow/dead: '.$p['inventory']['dead_slow_count'],'Health: '.(null===$p['inventory']['health_average']?'—':$p['inventory']['health_average'].'/100'),'Alerts: '.$p['operations']['critical_alerts'].' critical, '.$p['operations']['warning_alerts'].' warning','Bundle opportunities: '.$p['operations']['bundle_opportunities']);foreach($p['purchasing']['cash_by_currency'] as $c=>$v){$lines[]='90-day purchasing cash '.$c.': '.$v;}return implode("\n",$lines);}
 private static function date($d){$d=substr((string)$d,0,10);$x=DateTime::createFromFormat('Y-m-d',$d);return $x&&$x->format('Y-m-d')===$d?$d:null;}
}
